import { ArticleStatus } from "./types";

export const ALERT_STATUSES: Set<ArticleStatus> = new Set([
  "retracted",
  "withdrawn",
  "expression_of_concern",
]);

export const MAX_REFERENCE_CONCURRENCY = 4;
export const MAX_REFERENCED_DOIS = 10000;
export const SUPPORT_URL = "https://Luca-Dellanna.com/contact";
export const DONATE_URL = "https://new.Luca-Dellanna.com/donate";
export const ABOUT_URL = "https://Luca-Dellanna.com/retraction-alert";
export const STORE_URL =
  "https://chromewebstore.google.com/detail/retraction-alert/lcpdiodcbbmlgindmohlahaeglflacjb";
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
export const UNKNOWN_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes for unknown results
export const CROSSREF_RATE_LIMIT_MS = 100; // ~10 req/s spacing
export const CROSSREF_MAX_RETRIES = 2;

export function getCrossrefUserAgent(): string {
  const version =
    typeof chrome !== "undefined" &&
    chrome.runtime?.getManifest &&
    chrome.runtime.getManifest()?.version
      ? chrome.runtime.getManifest().version
      : "0.0.0";
  return `RetractionAlert/${version} (${SUPPORT_URL})`;
}

export const NEWS_CONTACTS: Record<string, string> = {
  "wsj.com": "wsjcontact@wsj.com",
  "theguardian.com": "reader@theguardian.com",
  "nytimes.com": "letters@nytimes.com",
  "washingtonpost.com": "letters@washpost.com",
  "economist.com": "letters@economist.com",
  "ft.com": "customer.support@ft.com",
  "bbc.com": "haveyoursay@bbc.co.uk",
  "reuters.com": "editor@reuters.com",
  "latimes.com": "readers.rep@latimes.com",
  "nbcnews.com": "tips@nbcuni.com",
  "cnn.com": "cnntips@cnn.com",
  "abc.net.au": "",
  "elpais.com": "",
  "elmundo.es": "",
  "lavanguardia.com": "",
  "faz.net": "",
  "globo.com": "",
  "lemonde.fr": "",
  "lefigaro.fr": "",
  "lastampa.it": "",
  "repubblica.it": "",
  "bild.de": "",
  "zeit.de": "",
  "spiegel.de": "",
  "theage.com.au": "",
  "telegraph.co.uk": "",
  "independent.co.uk": "",
  "thetimes.co.uk": "",
  "linkedin.com": "",
};

export const SCIENCE_HOSTS = [
  "doi.org",
  "nature.com",
  "thelancet.com",
  "science.org",
  "sciencedirect.com",
  "link.springer.com",
  "onlinelibrary.wiley.com",
  "tandfonline.com",
  "jamanetwork.com",
  "nejm.org",
  "bmj.com",
  "journals.plos.org",
  "pubs.acs.org",
  "ieeexplore.ieee.org",
  "dl.acm.org",
  "arxiv.org",
  "biorxiv.org",
  "medrxiv.org",
  "academic.oup.com",
  "psycnet.apa.org",
  "cambridge.org",
  "nlm.nih.gov",
  "nih.gov",
  "pnas.org",
  "cell.com",
  "frontiersin.org",
  "mdpi.com",
  "scielo.br",
  "scielo.org",
  "hindawi.com",
  "sagepub.com",
  "biomedcentral.com",
  "karger.com",
  "rsc.org",
  "iopscience.iop.org",
  "spiedigitallibrary.org",
  "aip.scitation.org",
  "journals.lww.com",
  "asm.org",
  "ahajournals.org",
  "royalsocietypublishing.org",
  "journals.aps.org",
  "aacrjournals.org",
  "ashpublications.org",
  "jci.org",
  "chestjournal.org",
  "diabetesjournals.org",
  "publications.aap.org",
  "psychiatryonline.org",
  "radiology.rsna.org",
  "scientificamerican.com",
  "sciencenews.org",
  "phys.org",
  "annualreviews.org",
  "liebertpub.com",
  "degruyter.com",
  "embopress.org",
  "microbiologyresearch.org",
  "bloodjournal.org",
  "f1000research.com",
  "peerj.com",
  "ersjournals.com",
  "ieee.org",
  "spandidos-publications.com",
  "thieme-connect.com",
  "aacnjournals.org",
  "oup.com",
  "springeropen.com",
  "biologists.com",
  "royalsociety.org",
  "pediatrics.aappublications.org",
  "aha.jamanetwork.com",
  "ascopubs.org",
  "asmjournals.org",
  "frontierspartnerships.org",
  "bmcanalytics.com",
  "thecvf.com",
  "openaccess.thecvf.com",
  "neurips.cc",
  "iclr.cc",
  "openreview.net",
  "icml.cc",
  "ecva.net",
  "cdc.gov",
];

export const NEWS_HOSTS = [
  "abc.net.au",
  "elpais.com",
  "elmundo.es",
  "lavanguardia.com",
  "faz.net",
  "globo.com",
  "corriere.it",
  "lemonde.fr",
  "lefigaro.fr",
  "lastampa.it",
  "repubblica.it",
  "bild.de",
  "zeit.de",
  "spiegel.de",
  "theage.com.au",
  "telegraph.co.uk",
  "independent.co.uk",
  "thetimes.co.uk",
  "wsj.com",
  "theguardian.com",
  "nytimes.com",
  "washingtonpost.com",
  "economist.com",
  "ft.com",
  "bbc.com",
  "reuters.com",
  "latimes.com",
  "nbcnews.com",
  "cnn.com",
  "nih.gov",
  "linkedin.com",
  "xinhuanet.com",
  "globaltimes.cn",
  "people.cn",
  "thehindu.com",
  "indianexpress.com",
  "hindustantimes.com",
  "ndtv.com",
  "livemint.com",
  "kompas.com",
  "detik.com",
  "tempo.co",
  "dawn.com",
  "tribune.com.pk",
  "thenews.com.pk",
  "punchng.com",
  "vanguardngr.com",
  "premiumtimesng.com",
  "folha.uol.com.br",
  "estadao.com.br",
  "theglobeandmail.com",
  "cbc.ca",
  "rt.com",
  "ria.ru",
  "interfax.ru",
  "eluniversal.com.mx",
  "reforma.com",
  "milenio.com",
  "thedailystar.net",
  "prothomalo.com",
  "japantimes.co.jp",
  "asahi.com",
  "yomiuri.co.jp",
  "straitstimes.com",
  "channelnewsasia.com",
  "taipeitimes.com",
  "politico.eu",
  "euronews.com",
  "rte.ie",
  "irishtimes.com",
  "derstandard.at",
  "scmp.com",
  "southchina.com",
  "bbc.co.uk",
  "msn.com",
  "finance.yahoo.com",
  "news.yahoo.com",
  "news.google.com",
  "indiatimes.com",
  "news18.com",
  "foxnews.com",
  "bloomberg.com",
  "ilsole24ore.com",
  "people.com",
  "usatoday.com",
  "substack.com",
  "cnbc.com",
  "nypost.com",
  "apnews.com",
  "cbsnews.com",
  "indiatoday.in",
  "forbes.com",
  "oneindia.com",
  "india.com",
  "businessinsider.com",
  "abcnews.go.com",
  "politico.com",
  "buzzfeed.com",
  "news.com.au",
  "thesun.co.uk",
  "news.sky.com",
  "thehill.com",
  "aljazeera.com",
  "drudgereport.com",
  "rediff.com",
];
